### ISSUE TITLE
Implement the step to invite a user to create a new account

### ISSUE THREAD

**Issue by anandology** [fossunited/malgudi#10]
To create a new account:
-  the user will  click on the "Join Malgudi"  link on the navbar 
- enter the email address and submit the form
- receives an invite email in his mailbox and clicks the invite link
- the invitation page will ask for username and password
- the user enters these details and creates th account
- a welcome email is sent to him

JOIN URL: `/app/join`
INVITE URL: `/app/join/e2bfb064bcff44459c4d5d6a923bc283`

## Storage

The invite code (the last part of the invite url) is a UUID and that is stored in an invite table, mapping it with the email address and the expiry date. There could be more than one invite per email (should we allow this?) and all of them will be valid.

## Tasks

- [ ] Add a "Join Malgudi" button on the navbar
- [ ] join page with a form to enter email address
- [ ] on submit send email with invite link and respond with acknowledge message

---
Story #6
